# Generated by Django 4.2.30 on 2026-08-24 21:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "EMAIL_UNIQUE",
                    models.BooleanField(default=True, verbose_name="Email Único"),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "preferencias",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Preferências"
                    ),
                ),
                ("anonimo", models.BooleanField(default=True, verbose_name="Anônimo")),
                (
                    "ultimo_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Login"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "db_table": "usuario",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Configuracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave",
                    models.CharField(
                        choices=[
                            ("LIMITE_VOLUME_COMBUSTIVEL", "Limite Volume Combustível"),
                            ("LIMITE_EMENDAS_PIX", "Limite Emendas Pix"),
                            ("CACHE_TTL_SEGUNDOS", "Cache TTL segundos"),
                            ("MAX_DEPUTADOS_POR_BATCH", "Max Deputados por Batch"),
                            ("TIMEOUT_API_SEGUNDOS", "Timeout API segundos"),
                            ("ANO_ATUAL", "Ano Atual"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Chave",
                    ),
                ),
                ("valor", models.CharField(max_length=500, verbose_name="Valor")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Tipo"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configuração",
                "verbose_name_plural": "Configurações",
                "db_table": "configuracao",
            },
        ),
        migrations.CreateModel(
            name="Politico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_civil",
                    models.CharField(max_length=255, verbose_name="Nome Civil"),
                ),
                (
                    "nome_social",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome Social",
                    ),
                ),
                (
                    "partido",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Partido"
                    ),
                ),
                (
                    "uf",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="UF deve ser o código de 2 letras do estado",
                                regex="^[A-Z]{2}$",
                            )
                        ],
                        verbose_name="UF",
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Município"
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                        null=True,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "grau_instrucao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Grau de Instrução",
                    ),
                ),
                (
                    "ocupacao",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ocupação"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Político",
                "verbose_name_plural": "Políticos",
                "db_table": "politico",
                "ordering": ["nome_civil"],
            },
        ),
        migrations.CreateModel(
            name="Mandato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("Presidente", "Presidente"),
                            ("Vice-Presidente", "Vice-Presidente"),
                            ("Governador", "Governador"),
                            ("Vice-Governador", "Vice-Governador"),
                            ("Senador", "Senador"),
                            ("Deputado Federal", "Deputado Federal"),
                            ("Deputado Estadual", "Deputado Estadual"),
                            ("Prefeito", "Prefeito"),
                            ("Vice-Prefeito", "Vice-Prefeito"),
                            ("Vereador", "Vereador"),
                            ("Ministro", "Ministro"),
                            ("Secretário", "Secretário"),
                            ("Secretário Municipal", "Secretário Municipal"),
                        ],
                        max_length=50,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "esfera",
                    models.CharField(
                        choices=[
                            ("Federal", "Federal"),
                            ("Estadual", "Estadual"),
                            ("Municipal", "Municipal"),
                        ],
                        max_length=20,
                        verbose_name="Esfera",
                    ),
                ),
                (
                    "estado_uf",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="UF deve ser o código de 2 letras do estado",
                                regex="^[A-Z]{2}$",
                            )
                        ],
                        verbose_name="UF",
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Município"
                    ),
                ),
                (
                    "ano_inicio",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ano de Início"
                    ),
                ),
                (
                    "ano_fim",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ano de Fim"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "politico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandatos",
                        to="politik_django.politico",
                        verbose_name="Político",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandato",
                "verbose_name_plural": "Mandatos",
                "db_table": "mandato",
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CNPJ deve ter 14 dígitos", regex="^\\d{14}$"
                            )
                        ],
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=255, verbose_name="Razão Social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome Fantasia",
                    ),
                ),
                (
                    "situacao_cadastral",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ATIVA", "Ativa"),
                            ("INAPTA", "Inapta"),
                            ("SUSPENSA", "Suspensa"),
                            ("BAIXADA", "Baixada"),
                            ("NULO", "Nulo"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Situação Cadastral",
                    ),
                ),
                (
                    "data_situacao_cadastral",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Situação Cadastral"
                    ),
                ),
                (
                    "data_inicio_atividade",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Início Atividade"
                    ),
                ),
                (
                    "cnae_fiscal",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="CNAE Fiscal"
                    ),
                ),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bairro"
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Município"
                    ),
                ),
                (
                    "uf",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="UF deve ser o código de 2 letras do estado",
                                regex="^[A-Z]{2}$",
                            )
                        ],
                        verbose_name="UF",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="CEP"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "db_table": "fornecedor",
                "indexes": [
                    models.Index(
                        fields=["cnpj", "situacao_cadastral"],
                        name="fornecedor_cnpj_79dc46_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Cota Parlamentar", "Cota Parlamentar"),
                            ("Emendas Pix", "Emendas Pix"),
                            ("Emendas de Comissão", "Emendas de Comissão"),
                            ("Salários", "Salários"),
                            ("Auxílio-Moradia", "Auxílio-Moradia"),
                            (
                                "Combustíveis e Lubrificantes",
                                "Combustíveis e Lubrificantes",
                            ),
                            ("Passagens Aéreas", "Passagens Aéreas"),
                            ("Consultorias e Pesquisas", "Consultorias e Pesquisas"),
                            ("Serviços de Saúde", "Serviços de Saúde"),
                            ("Educação", "Educação"),
                            ("Outros", "Outros"),
                        ],
                        max_length=100,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "subcategoria",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Subcategoria",
                    ),
                ),
                (
                    "tipo_verba",
                    models.CharField(max_length=255, verbose_name="Tipo de Verba"),
                ),
                (
                    "descricao_despesa",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição da Despesa"
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Número do Documento",
                    ),
                ),
                (
                    "valor_liquidado",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Valor Liquidado"
                    ),
                ),
                (
                    "valor_empenhado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Empenhado",
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "valor_desconto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Desconto",
                    ),
                ),
                ("data_emissao", models.DateField(verbose_name="Data de Emissão")),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                (
                    "numero_parcela",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número da Parcela"
                    ),
                ),
                (
                    "parcela",
                    models.IntegerField(blank=True, null=True, verbose_name="Parcela"),
                ),
                (
                    "url_documento",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL do Documento"
                    ),
                ),
                ("fonte", models.CharField(max_length=50, verbose_name="Fonte")),
                ("ano", models.IntegerField(verbose_name="Ano")),
                ("mes", models.IntegerField(blank=True, null=True, verbose_name="Mês")),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="despesas",
                        to="politik_django.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "mandato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas",
                        to="politik_django.mandato",
                        verbose_name="Mandato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
                "db_table": "despesa",
                "ordering": ["-data_emissao", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Assinatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_notificacao",
                    models.CharField(
                        choices=[("email", "Email"), ("push", "Push"), ("sms", "SMS")],
                        default="email",
                        max_length=20,
                        verbose_name="Tipo de Notificação",
                    ),
                ),
                (
                    "frequencia",
                    models.CharField(
                        choices=[
                            ("imediata", "Imediata"),
                            ("diaria", "Diária"),
                            ("semanal", "Semanal"),
                        ],
                        default="imediata",
                        max_length=20,
                        verbose_name="Frequência",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "mandato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="politik_django.mandato",
                        verbose_name="Mandato",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura",
                "verbose_name_plural": "Assinaturas",
                "db_table": "assinatura",
            },
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("anomalia", "Anomalia"),
                            ("volume", "Volume"),
                            ("suspeita", "Suspeita"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "severidade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        max_length=20,
                        verbose_name="Severidade",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "valor_trigger",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Trigger",
                    ),
                ),
                (
                    "valor_real",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Valor Real",
                    ),
                ),
                (
                    "referencia_cnpj",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        verbose_name="CNPJ Referência",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Criado em"
                    ),
                ),
                (
                    "resolvido",
                    models.BooleanField(default=False, verbose_name="Resolvido"),
                ),
                (
                    "resolvido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolvido em"
                    ),
                ),
                (
                    "mandato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="politik_django.mandato",
                        verbose_name="Mandato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "db_table": "alerta",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddIndex(
            model_name="mandato",
            index=models.Index(
                fields=["politico", "cargo", "esfera"],
                name="mandato_politic_e47d91_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mandato",
            unique_together={("politico", "cargo", "ano_inicio")},
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(
                fields=["mandato", "ano", "mes"], name="despesa_mandato_347028_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(fields=["categoria"], name="despesa_categor_97fb9f_idx"),
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(
                fields=["valor_liquidado"], name="despesa_valor_l_ac61c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(
                fields=["-valor_liquidado"], name="despesa_valor_l_cdc697_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(
                fields=["data_emissao"], name="despesa_data_em_e3fb98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(
                fields=["-data_emissao"], name="despesa_data_em_288096_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(fields=["fonte"], name="despesa_fonte_54e468_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="assinatura",
            unique_together={("usuario", "mandato")},
        ),
        migrations.AddIndex(
            model_name="alerta",
            index=models.Index(
                fields=["tipo", "severidade"], name="alerta_tipo_ab9926_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerta",
            index=models.Index(fields=["criado_em"], name="alerta_criado__e1a3e9_idx"),
        ),
    ]
