# Generated by Django 4.2.30 on 2026-08-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("politik_django", "0002_despesa_processado_em"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="despesa",
            new_name="despesa_process_d2f8f7_idx",
            old_name="despesa_processado_em_id_7f9c4e_idx",
        ),
    ]
