# Generated by Django 4.2.30 on 2026-08-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politik_django', '0003_rename_despesa_processado_em_id_7f9c4e_idx_despesa_process_d2f8f7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='capital_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Capital Social'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='natureza_juridica',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Natureza Jurídica'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='ultima_atualizacao_receita',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última consulta à Receita'),
        ),
    ]
