# Generated by Django 4.2.30 on 2026-08-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politik_django', '0004_fornecedor_capital_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandato',
            name='score_risco',
            field=models.IntegerField(default=0, help_text='0-100: Quanto maior, mais anomalias', verbose_name='Score de Risco'),
        ),
    ]
