# Generated by Django 4.2.30 on 2026-08-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politik_django', '0005_mandato_score_risco'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='quadro_societario',
            field=models.JSONField(blank=True, null=True, verbose_name='Quadro Societário (QSA)'),
        ),
    ]
