# Generated by Django 4.2.30 on 2026-08-29 03:01

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('politik_django', '0006_fornecedor_quadro_societario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Chave de Acesso (API Key)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('requisicoes_mes', models.IntegerField(default=0, verbose_name='Requisições este mês')),
                ('limite_requisicoes', models.IntegerField(default=1000, verbose_name='Limite de requisições')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
