# Generated by Django 4.2.30 on 2026-08-29 03:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('politik_django', '0007_clienteapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaEleitoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano da Eleição')),
                ('cargo_disputado', models.CharField(max_length=100, verbose_name='Cargo Disputado')),
                ('uf_disputada', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Disputada')),
                ('numero_urna', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número na Urna')),
                ('resultado', models.CharField(choices=[('ELEITO', 'Eleito'), ('NAO_ELEITO', 'Não Eleito'), ('SUPLENTE', 'Suplente'), ('RENUNCIA', 'Renúncia'), ('INDEFERIDO', 'Indeferido'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30, verbose_name='Resultado')),
                ('limite_gastos', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Limite de Gastos')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('politico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas', to='politik_django.politico', verbose_name='Político')),
            ],
            options={
                'verbose_name': 'Campanha Eleitoral',
                'verbose_name_plural': 'Campanhas Eleitorais',
                'db_table': 'campanha_eleitoral',
                'unique_together': {('politico', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='ReceitaCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('FEFC', 'Fundo Especial (FEFC)'), ('FUNDO_PARTIDARIO', 'Fundo Partidário'), ('DOACAO_PF', 'Doação Pessoa Física'), ('DOACAO_PJ', 'Doação Pessoa Jurídica'), ('PROPRIO', 'Recursos Próprios'), ('OUTRO', 'Outros Recursos')], default='OUTRO', max_length=30, verbose_name='Origem do Recurso')),
                ('cpf_cnpj_doador', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF/CNPJ do Doador')),
                ('nome_doador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Doador')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Recebido')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data do Recebimento')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='politik_django.campanhaeleitoral', verbose_name='Campanha')),
            ],
            options={
                'verbose_name': 'Receita de Campanha',
                'verbose_name_plural': 'Receitas de Campanha',
                'db_table': 'receita_campanha',
                'indexes': [models.Index(fields=['cpf_cnpj_doador'], name='receita_cam_cpf_cnp_e93fcf_idx'), models.Index(fields=['origem'], name='receita_cam_origem_4f2b0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DespesaCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj_fornecedor', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF/CNPJ na Nota')),
                ('nome_fornecedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome na Nota')),
                ('tipo_despesa', models.CharField(max_length=255, verbose_name='Tipo de Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Gasto')),
                ('data_despesa', models.DateField(blank=True, null=True, verbose_name='Data da Despesa')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='politik_django.campanhaeleitoral', verbose_name='Campanha')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_campanha', to='politik_django.fornecedor', verbose_name='Fornecedor Contratado')),
            ],
            options={
                'verbose_name': 'Despesa de Campanha',
                'verbose_name_plural': 'Despesas de Campanha',
                'db_table': 'despesa_campanha',
                'indexes': [models.Index(fields=['cpf_cnpj_fornecedor'], name='despesa_cam_cpf_cnp_5cd3e5_idx'), models.Index(fields=['tipo_despesa'], name='despesa_cam_tipo_de_42722f_idx')],
            },
        ),
    ]
