# Generated by Django 4.2.30 on 2026-08-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politik_django', '0008_campanhaeleitoral_receitacampanha_despesacampanha'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmendaParlamentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('tipo_emenda', models.CharField(choices=[('PIX', 'Transferência Especial (Emenda Pix)'), ('INDIVIDUAL', 'Emenda Individual (RP6)'), ('BANCADA', 'Emenda de Bancada (RP7)'), ('RELATOR', 'Emenda de Relator (RP9)'), ('COMISSAO', 'Emenda de Comissão (RP8)'), ('OUTROS', 'Outros Tipos')], default='OUTROS', max_length=50)),
                ('numero_emenda', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiario', models.CharField(help_text='Município, Estado ou Entidade', max_length=255)),
                ('uf_beneficiario', models.CharField(blank=True, max_length=2, null=True)),
                ('valor_empenhado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('politico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emendas', to='politik_django.politico')),
            ],
            options={
                'indexes': [models.Index(fields=['politico', 'ano'], name='politik_dja_politic_4e92ee_idx'), models.Index(fields=['tipo_emenda'], name='politik_dja_tipo_em_b649a7_idx')],
            },
        ),
    ]
