name: Pipeline de Ingestao de Dados

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  ingestao_supabase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias do Projeto
        run: pip install requests supabase

      - name: Executar Motor de Extracao e Insercao
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python coleta_dados.py
