name: Atualizar
on: [workflow_dispatch]
permissions: contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install requests
      - run: python coleta_dados.py
      - name: Commit e Push
        run: |
          git config user.name "Bot"
          git config user.email "bot@bot.com"
          git add dados.json
          git commit -m "Atualiza dados" || exit 0
          git push
          
